config/routes.rb
Clipjet::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' # Feel free to change '/admin' to any namespace you need.
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
  
  resources :categories, only: :index
  # resources :hit, only: [:create, :update]
  scope "/api" do
    get 'hit/create' => 'hit#create'
    get 'hit/update' => 'hit#update'
    
    # resources :video, only: :show
    get 'videos/show' => 'video#show'

  end
  
  resources :influencer_views, only: [:create, :update]

  resources :sites, only: [] do
    resource :widget, only: :show
  end

  resources :payment_notifications, only: :create

  match 'iv/:id', to: 'influencer_shared_videos#show', via: :get, as: :shared_video

  scope '(:locale)', :locale => /en|es/ do
    devise_for :publishers

    devise_for :advertisers

    devise_for :users, controllers: {registrations: "registrations"}

    root :to => "static#home"

    resources :sites, only: [:new, :create, :index, :destroy] do 
      resources :widget_installs, only: :index
      resources :views, only: :index
      resources :earnings, only: :index
    end

    resources :users, only: :update
    resources :withdrawal_requests, only: :create

    # resources :influencer_videos, only: :index

    match 'influencer/campaigns', to: 'influencer_campaigns#index', via: :get
    # match 'influencer/videos/:id', to: 'influencer_videos#show', via: :get, as: :influencer_video

    resources :influencer_videos, only: [:create, :show, :index]

    resources :finances, only: :index
    resource :campaign_completion, only: :new
    resources :campaigns, only: [:index, :new, :create, :edit, :update] do
      resources :credits_purchases, only: :new
      resources :impressions, only: :index
      member do
        get '/views' => 'campaign_views#index'
        post '/set_payment_params' => 'credits_purchases#params_encryption'
      end
    end
    resource :video_registration, only: [:new, :create]

    get 'welcome' => 'publishers#welcome', as: :publisher_root
    get "promote" => 'video#advertiser_pay', as: :advertiser_root

    get "publishers" => 'static#publishers', as: :publisher
    get "faq" => 'static#faq', as: :faq
    get "influencers" => 'static#influencers', as: :influencer
    
  end
  
  
  
  
end

app/views/shared/_campaign_stats_hero.html.erb
<% content_for :manage_campaigns do %>
  active
<% end %>

<section class="hero">
  <h1><%= hero %></h1>
</section>

app/views/shared/_footer.html.erb
<div class="footer-wrapper">
  <footer class="clearfix">
      <%= link_to root_path, class: 'pull-left' do %>
        <h1 class="hide-text">CLIPJET</h1>
      <% end %>
      <nav>
        <ul>
          <li class="pull-left"><%= link_to t('shared.header.promote_your_videos'), root_path %></li>
          <li class="pull-left"><%= link_to t('shared.header.become_a_publisher'), publisher_path %></li>
          <li class="pull-left"><%= link_to t('shared.header.become_an_influencer'), influencer_path %></li>
          <li class="pull-left"><%= link_to t('.faq'), faq_path %></li>
<!--           <li class="pull-left"><a href="#">About Clipjet</a></li>
          <li class="pull-left"><a href="#">FAQ</a></li> -->
        </ul>
      </nav>
      <%= form_tag '', class: 'locale pull-right'  do %>
        <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s) %>
      <% end %>
  </footer>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <header class="clearfix">
    <%= link_to root_path, class: 'pull-left' do %>
      <h1 class="hide-text">CLIPJET</h1>
    <% end %>
    <nav>
      <ul>
        <% if promoter_controller? %>
          <%= render 'shared/nav_promoter' %>
        <% elsif publisher_controller? %>
          <%= render 'shared/nav_publisher' %>
        <% elsif influencer_controller? %>
          <%= render 'shared/nav_influencer' %>
        <% else %>
          <li class="pull-left"><%= link_to t('.promote_your_videos'), root_path %></li>
          <li class="pull-left"><%= link_to t('.become_a_publisher'), publisher_path %></li>
          <li class="pull-left"><%= link_to t('.become_an_influencer'), influencer_path %></li>
        <% end %>
      </ul>
    </nav>

    <nav class="session-nav">
      <ul>
        <% if user_signed_in? %>
          <li class="right"><%= link_to t(".log_out"), destroy_user_session_path, method: :delete %></li>
          <li class="dropdown right">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle"><%= t '.profile' %><b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
              <li><%= link_to t(".promoter"), new_video_registration_path %></li>
              <li><%= link_to t(".publisher"), new_site_path %></li>
              <li><%= link_to t(".influencer"), influencer_campaigns_path %></li>
            </ul>
          </li>
        <% else %>
          <li class="right"><%= link_to t(".sign_up"), new_user_registration_path, class: 'button' %></li>
          <li class="right"><%= link_to t(".login"), new_user_session_path, class: 'login' %></li>
        <% end %>
      </ul>
    </nav>
  </header>
</div>

app/views/shared/_install_clipjet_hero.html.erb
<% content_for :install_clipjet do %>
  active
<% end %>

<section class="hero">
  <h1><%= t '.install_clipjet' %></h1>
</section>

app/views/shared/_nav_influencer.html.erb
<li><%= link_to t(".pick_a_clip"), influencer_campaigns_path, class: "pull-left #{yield :pick_a_clip}" %></li>
<li><%= link_to t(".your_shared_videos"), influencer_videos_path, class: "pull-left #{yield :your_shared_videos}" %></li>
<li><%= link_to t(".your_finances"), finances_path, class: "pull-left #{yield :finances}" %></li>

app/views/shared/_nav_promoter.html.erb
<li><%= link_to t(".promote_video"), new_video_registration_path, class: "pull-left #{yield :promote_video}" %></li>
<li><%= link_to t(".manage_campaigns"), campaigns_path, class: "pull-left #{yield :manage_campaigns}" %></a></li>

app/views/shared/_nav_publisher.html.erb
<li><%= link_to t(".install_clipjet"), new_site_path, class: "pull-left #{yield :install_clipjet}" %></li>
<li><%= link_to t(".account_stats"), sites_path, class: "pull-left #{yield :account_stats}" %></li>
<li><%= link_to t(".your_finances"), finances_path, class: "pull-left #{yield :finances}" %></li>

app/views/shared/_new_campaign_hero.html.erb
<% content_for :promote_video do %>
  active
<% end %>
<section class="hero">
  <h1><%= t '.promote_video' %></h1>
</section>

app/views/shared/_paypal_popup.html.erb
<div class="popup hidden">
	<div><div class="close rounded">X</div>

	</div>
</div>

app/views/shared/_pick_clip_hero.html.erb
<% content_for :pick_a_clip do %>
  active
<% end %>

<section class="hero">
  <h1><%= hero %></h1>
</section>

app/views/shared/_publisher_stats_hero.html.erb
<% content_for :account_stats do %>
  active
<% end %>

<section class="hero">
  <h1><%= hero %></h1>
</section>